# This is a basic workflow to help you get started with Actions

name: Python script

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a Python script
        run: python .github/workflows/example.py

 # Add new files in folder, commit along with other modified files, push
      - id: commit
        name: Commit files
        run:
          git config --local user.name actions-user

          git config --local user.email "actions@github.com"

          git add *

          git commit -am "GH ACTION Headlines $(date)"

          git push origin main

        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}

          username: github-actions
